### ISSUE TITLE
Bad http request error

### ISSUE THREAD

**Issue by adamsorbie** [lozuponelab/AMON#10]
Hi, 

I am getting a bad http request error when trying to run AMON. Doesn't seem to matter what I use as input, even with 10 KO's as input I still get the same error. 

$ amon.py -i amon_input/picrust_kos.tsv --detected_compounds amon_input/AMON_input-metabolome.tsv --other_gene_set_name amon_input/mouse_genome_ko_list.tsv -o amon_output

Traceback (most recent call last):
  File "C:/Users/adamsorbie/miniconda3/envs/amon/Scripts/amon.py", line 76, in <module>
    co_file_loc=co_file_loc, pathway_file_loc=pathway_file_loc, write_json=write_json)
  File "C:\Users\adamsorbie\miniconda3\envs\amon\lib\site-packages\AMON\predict_metabolites.py", line 283, in main
    ko_dict = get_kegg_record_dict(set(all_kos), parse_ko, ko_file_loc)
  File "C:\Users\adamsorbie\miniconda3\envs\amon\lib\site-packages\KEGG_parser\downloader.py", line 55, in get_kegg_record_dict
    records = get_from_kegg_api(loop, list_of_ids, parser)
  File "C:\Users\adamsorbie\miniconda3\envs\amon\lib\site-packages\KEGG_parser\downloader.py", line 49, in get_from_kegg_api
    return [parser(raw_record) for raw_record in loop.run_until_complete(kegg_download_manager(loop, list_of_ids))]
  File "C:\Users\adamsorbie\miniconda3\envs\amon\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:\Users\adamsorbie\miniconda3\envs\amon\lib\site-packages\KEGG_parser\downloader.py", line 43, in kegg_download_manager
    results = await asyncio.gather(*tasks)
  File "C:\Users\adamsorbie\miniconda3\envs\amon\lib\site-packages\KEGG_parser\downloader.py", line 32, in download_coroutine
    raise ValueError('Bad HTTP request status %s: %s\n%s' % (response.status, response.reason, url))
ValueError: Bad HTTP request status 400: Bad Request
http://rest.kegg.jp/get/Unnamed: 2+Unnamed: 3+Unnamed: 1+1

Do you have any idea why this is happening?

**Comment by luozhy88** [comment]
I also have the same bug.
![image](https://user-images.githubusercontent.com/94740863/159105478-473db1d1-6830-4baf-8e45-a12a61149de1.png)

**Comment by salverna** [comment]
I am also getting the same bug

**Comment by duu-123** [comment]
Me, too
