### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by mrgambero** [lozuponelab/AMON#13]
Hello,
Thanks for your work.

I am trying to tun AMON but I do not seem to be able to get any results out.

Specifically, I always encounter this problem:
amon.py -i Komicro.txt -o output_AMON --detected_compounds COlist1.txt --other_gene_set mus_mucus1.txt
Traceback (most recent call last):
  File "/Users/gabri/opt/miniconda3/envs/AMON/bin/amon.py", line 74, in <module>
    main(kos_loc, output_dir, other_kos_loc, detected_compounds, name1, name2, keep_separated, samples_are_columns,
  File "/Users/gabri/opt/miniconda3/envs/AMON/lib/python3.10/site-packages/AMON/predict_metabolites.py", line 283, in main
    ko_dict = get_kegg_record_dict(set(all_kos), parse_ko, ko_file_loc)
  File "/Users/gabri/opt/miniconda3/envs/AMON/lib/python3.10/site-packages/KEGG_parser/downloader.py", line 55, in get_kegg_record_dict
    records = get_from_kegg_api(loop, list_of_ids, parser)
  File "/Users/gabri/opt/miniconda3/envs/AMON/lib/python3.10/site-packages/KEGG_parser/downloader.py", line 49, in get_from_kegg_api
    return [parser(raw_record) for raw_record in loop.run_until_complete(kegg_download_manager(loop, list_of_ids))]
  File "/Users/gabri/opt/miniconda3/envs/AMON/lib/python3.10/site-packages/KEGG_parser/downloader.py", line 49, in <listcomp>
    return [parser(raw_record) for raw_record in loop.run_until_complete(kegg_download_manager(loop, list_of_ids))]
  File "/Users/gabri/opt/miniconda3/envs/AMON/lib/python3.10/site-packages/KEGG_parser/parsers.py", line 195, in parse_ko
    raise ValueError('What is {} in {}?'.format(current_entry_name, ko_dict['ENTRY']))
ValueError: What is SYMBOL in K09637?

Any idea of why this is happening?

Thanks in advance!
Gabri

**Comment by mrgambero** [comment]
Hello all,

No solution yet to this day.
How about you, Ilaira?


Gabri

**Comment by mrgambero** [comment]
Noone, It wold be very cool to have this tool functioning!

**Comment by sterrettJD** [comment]
Hi @mrgambero and @Hela06, I've been working on a fix to this issue. I believe it's actually an issue with KEGG_parser, rather than AMON itself. Sorry about the delay on this, but I'll keep you posted on progress!

**Comment by mrgambero** [comment]
Hello @sterrettJD thanks a lot! Yes keep me posted please!

Gabri

**Comment by mrgambero** [comment]
Hi everyone,

Still no AMON :(.
Anyone with any news?


Gabri

**Comment by sterrettJD** [comment]
Hey @mrgambero, good news! We think we have the issue in `KEGG-Parser` that was causing this patched, and I just pushed the new version to PyPI.

Could you run `pip install --upgrade KEGG-Parser` and then try to run AMON again? This should fix the `ValueError: What is SYMBOL in ...` (I hope).

Please let me know if upgrading KEGG-Parser to 0.0.5 fixes things!

**Comment by mrgambero** [comment]
Hello, sorry for the delay.
I now get this error:
amon.py -o /Users/gabri/Library/CloudStorage/Box-Box/CPAE_manuscript/metabolites/AMON -i /Users/gabri/Library/CloudStorage/Box-Box/CPAE_manuscript/metabolites/ko_list_metagen.txt --other_gene_set /Users/gabri/Library/CloudStorage/Box-Box/CPAE_manuscript/metabolites/Ko_Human.txt
Traceback (most recent call last):
  File "/Users/gabri/mambaforge/envs/AMON/lib/python3.11/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gabri/mambaforge/envs/AMON/lib/python3.11/asyncio/base_events.py", line 1085, in create_connection
    raise exceptions[0]
  File "/Users/gabri/mambaforge/envs/AMON/lib/python3.11/asyncio/base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gabri/mambaforge/envs/AMON/lib/python3.11/asyncio/base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "/Users/gabri/mambaforge/envs/AMON/lib/python3.11/asyncio/selector_events.py", line 634, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/Users/gabri/mambaforge/envs/AMON/lib/python3.11/asyncio/selector_events.py", line 674, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 60] Connect call failed ('133.103.200.27', 80)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/gabri/mambaforge/envs/AMON/bin/amon.py", line 74, in <module>
    main(kos_loc, output_dir, other_kos_loc, detected_compounds, name1, name2, keep_separated, samples_are_columns,
  File "/Users/gabri/mambaforge/envs/AMON/lib/python3.11/site-packages/AMON/predict_metabolites.py", line 283, in main
    ko_dict = get_kegg_record_dict(set(all_kos), parse_ko, ko_file_loc)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gabri/mambaforge/envs/AMON/lib/python3.11/site-packages/KEGG_parser/downloader.py", line 88, in get_kegg_record_dict
    records = get_from_kegg_api(loop, list_of_ids, parser)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gabri/mambaforge/envs/AMON/lib/python3.11/site-packages/KEGG_parser/downloader.py", line 78, in get_from_kegg_api
    return [parser(raw_record) for raw_record in loop.run_until_complete(kegg_download_manager(loop, list_of_ids))]
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gabri/mambaforge/envs/AMON/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/gabri/mambaforge/envs/AMON/lib/python3.11/site-packages/KEGG_parser/downloader.py", line 47, in kegg_download_manager
    results = await asyncio.gather(*tasks)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gabri/mambaforge/envs/AMON/lib/python3.11/site-packages/KEGG_parser/downloader.py", line 31, in download_coroutine
    async with session.get(url) as response:
  File "/Users/gabri/mambaforge/envs/AMON/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/Users/gabri/mambaforge/envs/AMON/lib/python3.11/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gabri/mambaforge/envs/AMON/lib/python3.11/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gabri/mambaforge/envs/AMON/lib/python3.11/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gabri/mambaforge/envs/AMON/lib/python3.11/site-packages/aiohttp/connector.py", line 1209, in _create_direct_connection
    raise last_exc
  File "/Users/gabri/mambaforge/envs/AMON/lib/python3.11/site-packages/aiohttp/connector.py", line 1178, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gabri/mambaforge/envs/AMON/lib/python3.11/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host rest.kegg.jp:80 ssl:default [Connect call failed ('133.103.200.27', 80)]
